channels:
  - defaults
dependencies:
  - defaults::numpy
  - defaults::pandas
  - defaults::nltk
  - defaults::scikit-learn
  - pytorch::pytorch
  - huggingface::datasets
  - huggingface::transformers
  - conda-forge::tqdm
